main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path('', view=views.index, name='index'),
    path('about/', view=views.about, name='about')
]

taskmanager/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls',namespace='main'))
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'main/index.html')

def about(request):
    return render(request, 'main/about.html')

main/templates/main/about.html
{% extends 'main/base.html' %}

{% block title %}Про сайт!{% endblock title %}

{% block content %}
<h1>Заголовок страницы про нас.</h1>
<p>Описание сайта, обзор возможностей этого приложения.</p>
{% endblock content %}

main/templates/main/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <div class="container">
        <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
          <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
            <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
            <span class="fs-4">Task Manager</span>
          </a>
    
          <ul class="nav nav-pills">
            <li class="nav-item"><a href="{% url "main:index" %}" class="nav-link">Главная</a></li>
            <li class="nav-item"><a href="{% url "main:about" %}" class="nav-link">О нас</a></li>
          </ul>
        </header>
      </div>

    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block title %}Главная страница!{% endblock title %}

{% block content %}
    <h1>Заголовок главной страницы.</h1>
    <p>Какой то текст на главной странице для примера.</p>
{% endblock content %}